1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np

In [ ]:
arr= np.empty((2,2))
print(arr)

array([[4.61628939e-315, 0.00000000e+000],
       [4.94065646e-324, 6.53119288e-310]])

2.Initialize an all one array with size 4X2.

In [ ]:
number=np.empty((4,2))
print(number)

[[4.67922788e-315 0.00000000e+000]
 [1.33856858e-152 2.44087854e-154]
 [4.65208813e+151 4.03504621e+087]
 [1.02189324e-152 2.59345433e+161]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
a= np.full((2,3),5)
print(a)

array([[5, 5, 5],
       [5, 5, 5]])

Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
b= np.zeros_like([[1,2,3],[4,5,6]])
print(b)

array([[0, 0, 0],
       [0, 0, 0]])

4.Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
c= np.ones_like([9,8,7])
print (c)

[1 1 1]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list=np.array([1,2,3,4])
print(new_list)

[1 2 3 4]


Task 2
1 Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
arr = np.arange(10,49)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


2 Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
arr= np.reshape([[1,2,3],[4,5,6],[7,8,9]],(3,3))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
ide=np.eye(3,3)
print(ide)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
arr=np.random.random(30)
print(arr)
print(np.mean(30))

[0.75216834 0.77419566 0.06115145 0.87351984 0.90242124 0.7086278
 0.72467216 0.17680649 0.95749933 0.05835059 0.98015911 0.55403809
 0.50998518 0.35898426 0.18634466 0.53660362 0.52348039 0.04646804
 0.07803622 0.00311858 0.1265294  0.38032548 0.05764041 0.21561701
 0.09519354 0.46061181 0.63634716 0.94978563 0.27378492 0.05357115]
30.0


5.Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
arr=np.random.random((10,10))
print(arr)

[[0.45682657 0.38247231 0.74751425 0.85414933 0.03550026 0.78916974
  0.53603503 0.79333268 0.0183383  0.20088148]
 [0.82125184 0.69383116 0.66104329 0.11177118 0.73627924 0.36420997
  0.45807341 0.3163375  0.22159429 0.98735812]
 [0.7946587  0.56282326 0.03870138 0.48379567 0.50535584 0.04244888
  0.6218207  0.88727181 0.02239351 0.37761029]
 [0.26660649 0.29103372 0.1938963  0.96062709 0.08775244 0.45795276
  0.62659225 0.35547535 0.75830169 0.70730909]
 [0.04002187 0.31085295 0.74371284 0.65829893 0.97065831 0.28010379
  0.6347862  0.53815332 0.35275987 0.98362821]
 [0.69971487 0.27708831 0.45782744 0.28707755 0.01682463 0.85999068
  0.59053004 0.68872844 0.94081388 0.87937977]
 [0.02874286 0.21942706 0.92864473 0.56918846 0.80566016 0.45031839
  0.61624092 0.02042615 0.46952392 0.32984145]
 [0.54483466 0.46840104 0.7376344  0.23633585 0.38185531 0.0807325
  0.46634345 0.43508955 0.05687711 0.16423671]
 [0.82221912 0.52950709 0.06339797 0.17278251 0.24896895 0.82597555
  0.45982928 

In [ ]:
minimum_value= arr.min()
maximum_value=arr.max()
print(minimum_value)
print(maximum_value)

0.01682462817200392
0.9873581154077188


6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
a= np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7.Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr=([1,2,0,0,4,0])
a=arr[::-1]
print(a)

[0, 4, 0, 0, 2, 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:

rows, cols =(5,5)
a= np.ones((rows,cols))
a[1:-1,1:-1] =0
print(a)



[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9.Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
rows ,cols=(8,8)
a=np.ones((rows,cols))
a[ 1::2, ::2]=0
a[ ::2, 1::2]=0
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


Task3 For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.

In [ ]:
x=np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
z=x+y
print(z)


[[ 6  8]
 [10 13]]


2. Subtract the two array.

In [ ]:
v = np.array([9,10]);
w = np.array([11,12]);
x=v-w
print(x)


[-2 -2]


3. Multiply the array with any integers of your choice.

In [ ]:
x = np.array([[1,2],[3,5]])
multiplication=x*3
print(multiplication)

[[ 3  6]
 [ 9 15]]


4. Find the square of each element of the array.

In [ ]:
w = np.array([11,12])
squared= w**2;
print(squared)

[121 144]


5.Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
v = np.array([9,10])
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
w = np.array([11,12])
print("The dot product of v and w is:", np.dot(v,w))
print("The dot product of x and v is:", np.dot(x,v))
print("The dot product of x and y is:", np.dot(x,y))


The dot product of v and w is: 219
The dot product of x and v is: [29 77]
The dot product of x and y is: [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
a = np.concatenate((x,y), axis=1);
print(a)
b=np.vstack((x,y))
print(b)

[[1 2 5 6]
 [3 5 7 8]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [ ]:
v = np.array([9,10]);
w = np.array([11,12]);
c = np.concatenate((v,w));
d = np.vstack((v,w));
print(c)
print(d)



[ 9 10 11 12]
[[ 9 10]
 [11 12]]


Task 4. 1.A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

In [ ]:
a = np.array([[3,4],[7,8]]);
b = np.array([[5,3],[2,1]]);
a_inv=np.linalg.inv(a)
print("This presents the inverse", a_inv)
I= np.dot(a, a_inv)
print("This presents the idenity matrix: ", I)
print( "Result:", np.allclose(I , np.eye(2)))



This presents the inverse [[-2.    1.  ]
 [ 1.75 -0.75]]
This presents the idenity matrix:  [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Result: True


2. Prove AB ̸= BA.

In [ ]:
a = np.array([[3,4], [7,8]]);
b = np.array([[5,3], [2,1]]);
ab = a @ b
ba = b @ a
print("AB: ", ab)
print("BA: ", ba)

print("Result:",np.array_equal(ab,ba))

AB:  [[23 13]
 [51 29]]
BA:  [[36 44]
 [13 16]]
Result: False


3. Prove (AB)T = BTAT.

In [ ]:
a = np.array([[3,4], [7,8]]);
b = np.array([[5,3], [2,1]]);
ab= a@b
ab_transpose=ab.T
b_transpose=b.T
a_transpose=a.T
b_transpose_a_transpose= b_transpose@a_transpose;
print("The transpose of AB",ab_transpose);
print("The transpose of b and a", b_transpose_a_transpose)
print("The output of AB transpose and B transpose A transpose: ", np.array_equal(ab_transpose, b_transpose_a_transpose))



The transpose of AB [[23 51]
 [13 29]]
The transpose of b and a [[23 51]
 [13 29]]
The output of AB transpose and B transpose A transpose:  True


2. Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

In [ ]:
import numpy as np

# Coefficient matrix
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Constant vector
b = np.array([-1, -3, 9])

# Compute inverse of A
A_inv = np.linalg.inv(A)

# Solve for x
x = A_inv @ b

print("Solution vector [x, y, z] =\n", x)


Solution vector [x, y, z] =
 [ 2.  1. -2.]
